version: '3'

services:
  client:
    build:
      context: redux-presentation/
      dockerfile: Dockerfile
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - '3000:3000'
    volumes:
      - ./redux-presentation:/app
      - rp_node_modules:/app/node_modules

volumes:
  rp_node_modules: